# Generated by Django 4.2.5 on 2023-10-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_product_cate_product_cat_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday',
            new_name='date_birthday',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
