# Generated by Django 4.2.5 on 2023-12-13 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_category_date_creation_category_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
